name: internal_lint
publish_to: none

resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  analysis_server_plugin: ^0.3.0
  analyzer: ^8.0.0
  analyzer_plugin: ^0.13.10
  riverpod_analyzer_utils:
    path: /Users/ext-remi.rousselet/dev/rrousselGit/riverpod/packages/riverpod_analyzer_utils
  meta: ^1.15.0
  path: ^1.8.1
  pubspec_parse: ^1.5.0
