name: riverpod_devtool
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.0-253.0.dev

resolution: workspace

dependencies:
  devtools_app_shared: ^0.4.0
  devtools_extensions: ^0.4.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  hooks_riverpod: 3.0.3
  intl: ^0.20.2
  stack_trace: ^1.12.1
  vm_service: ^15.0.2

dev_dependencies:
  build_runner: ^2.7.0
  flutter_test:
    sdk: flutter
  riverpod_devtool_generator: ^0.0.0

flutter:
  uses-material-design: true
