name: todos
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: "> 1.17.0"

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod:
    path: ../../packages/hooks_riverpod
  flutter_hooks: ^0.10.0
  uuid: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.0
  build_runner: ^1.9.0

flutter:
  uses-material-design: true
