name: riverpod_devtool_generator
publish_to: none

environment:
  sdk: ^3.8.0

resolution: workspace

dependencies:
  analyzer: ^9.0.0
  analyzer_buffer: ^0.3.0
  build: ^4.0.0
  build_config: ^1.1.0
  collection: ^1.17.1
  custom_lint_core: ^0.8.0
  dart_style: ^3.1.1
  meta: ^1.15.0
  path: ^1.9.0
  riverpod_analyzer_utils: ^1.0.0-dev.4
  source_gen: ^4.0.0
  source_span: ^1.10.0

dev_dependencies:
  build_runner: ^2.11.0
  build_test: ^3.2.1
  source_gen_test: ^1.0.4
