name: riverpod_example
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  crypto: ^3.0.0
  dio: ^4.0.0
  freezed_annotation: ^2.0.0
  riverpod:
    path: ..

dev_dependencies:
  build_runner: ^2.0.0
  freezed: ^2.0.0
  json_serializable: ^6.3.0
  test: ^1.16.0
