name: example
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  riverpod:
    path: ..
  freezed_annotation: ^0.7.1
  crypto: ^2.1.4
  dio: ^3.0.9

dev_dependencies:
  freezed: ^0.10.6
  json_serializable:
  build_runner: ^1.8.1