name: example
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  crypto: ^2.1.4
  dio: ^3.0.9
  freezed_annotation: ^0.11.0
  riverpod:
    path: ..

dev_dependencies:
  build_runner: ^1.8.1
  freezed: ^0.11.0
  json_serializable:
  test:
