name: riverpod_example
publish_to: "none"

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  crypto: ^3.0.0
  dio: ^5.1.1
  freezed_annotation: ^2.0.0
  json_annotation: ^4.6.0
  riverpod:
    path: ..

dev_dependencies:
  build_runner: ^2.0.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.0
  test: ^1.16.0
