name: stackoverflow
description: A new Flutter project.
publish_to: "none"

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  dio: 5.9.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  freezed_annotation: ^3.0.0
  hooks_riverpod:
  html: ^0.15.0
  json_annotation: ^4.9.0
  riverpod_annotation:

dev_dependencies:
  build_runner: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.0
  json_serializable: ^6.3.0
  mockito: ^5.0.0
  riverpod_generator:

flutter:
  uses-material-design: true
