name: riverpod_annotation
description: A package exposing annotations for riverpod_generator
version: 3.0.0-dev.14
repository: https://github.com/rrousselGit/riverpod
issue_tracker: https://github.com/rrousselGit/riverpod/issues
funding:
  - https://github.com/sponsors/rrousselGit/

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  meta: ^1.7.0
  riverpod: 3.0.0-dev.14

dev_dependencies:
  test: ^1.21.0
