name: riverpod_annotation
description: A package exposing annotations for riverpod_generator
version: 2.6.1
repository: https://github.com/rrousselGit/riverpod
issue_tracker: https://github.com/rrousselGit/riverpod/issues
funding:
  - https://github.com/sponsors/rrousselGit/

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  meta: ^1.7.0
  riverpod: 2.6.1

dev_dependencies:
  test: ^1.21.0
