name: riverpod_annotation
description: A package exposing annotations for riverpod_generator
version: 1.1.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  meta: ^1.7.0
  riverpod: 2.1.2

dev_dependencies:
  test: ^1.21.0
