name: flutter_riverpod
description: >
  A simple way to access state from anywhere in your application
  while robust and testable.
version: 3.0.0-dev.2
homepage: https://riverpod.dev
repository: https://github.com/rrousselGit/riverpod
issue_tracker: https://github.com/rrousselGit/riverpod/issues
funding:
  - https://github.com/sponsors/rrousselGit/

environment:
  sdk: ">=3.0.0+0.0-dev <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  meta: ^1.4.0
  riverpod: 3.0.0-dev.2
  state_notifier: ">=0.7.2 <2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  stack_trace: ^1.0.0
