name: flutter_riverpod
description: >
  A simple way to access state from anywhere in your application
  while robust and testable.
version: 0.13.0-nullsafety.3
homepage: https://riverpod.dev
repository: https://github.com/rrousselGit/river_pod

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ">=1.15.0-nullsafety.5 <2.0.0"
  flutter:
    sdk: flutter
  meta: ">=1.3.0-nullsafety.6 <2.0.0"
  riverpod: ^0.13.0-nullsafety.3
  state_notifier: ">=0.7.0-nullsafety.0 <1.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0-nullsafety.5
