name: riverpod_cli
description: A command line tool for Riverpod
version: 1.0.0-dev.5
homepage: https://riverpod.dev
repository: https://github.com/rrousselGit/river_pod

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: "^1.5.0"
  args: ^2.0.0
  codemod: ^1.0.1
  glob: ^2.0.1
  path: ^1.8.0
  pub_semver: ^2.0.0
  pubspec_parse: ^1.0.0

dev_dependencies:
  dart_style: any
  test: any

executables:
  riverpod: riverpod_cli
