name: riverpod_cli
description: A command line tool for Riverpod
version: 1.0.3
homepage: https://riverpod.dev
repository: https://github.com/rrousselGit/riverpod
issue_tracker: https://github.com/rrousselGit/riverpod/issues
funding:
  - https://github.com/sponsors/rrousselGit/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: "^1.5.0"
  args: ^2.0.0
  codemod: ^1.0.1
  collection: ^1.15.0
  glob: ^2.0.1
  meta: ^1.7.0
  path: ^1.8.0
  pub_semver: ^2.0.0
  pubspec_parse: ^1.0.0

dev_dependencies:
  dart_style: any
  test: any

executables:
  riverpod: riverpod_cli
