name: riverpod_cli
description: A command line tool for Riverpod
version: 0.0.2+1
homepage: https://riverpod.dev
repository: https://github.com/rrousselGit/river_pod

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  analyzer: ">=0.37.0 <0.40.0"
  args: ^1.5.0
  codemod: ^0.3.1
  glob: ^1.2.0
  path: ^1.8.0
  pub_semver: ^1.4.4
  pubspec_parse: ^0.1.8

dev_dependencies:
  dart_style: any
  test: any

executables:
  riverpod: riverpod_cli
