name: riverpod_sqflite
description: An adapter to connect riverpod_sqflite with Riverpod.
version: 0.1.0
environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  clock: ^1.1.1
  collection: ^1.14.0
  meta: ^1.15.0
  riverpod: 3.0.0-dev.13
  sqflite: ^2.4.1
  test: ^1.25.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  sqflite_common_ffi: ^2.3.4+4
