name: build_yaml
description: A sample command-line application.
publish_to: none

environment:
  sdk: ">=2.18.4 <4.0.0"

dependencies:
  riverpod:
  riverpod_annotation:

dev_dependencies:
  build_runner: ^2.3.2
  build_verify: ^3.0.0
  riverpod_generator:
  test: ^1.16.0
