name: hooks_riverpod_example
description: A new Flutter project.

publish_to: "none"

environment:
  sdk: ">=2.12.0-0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
