name: devtool
description: A new Flutter package project.
version: 0.0.1
homepage: https://riverpod.dev
authors:
  - Remi Rousselet <darky12s@gmail.com>

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.9.0
  freezed_annotation: ^0.11.0-dev
  hooks_riverpod:
    path: ../hooks_riverpod

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed: 0.11.0-dev

dependency_overrides:
  flutter_riverpod:
    path: ../../packages/flutter_riverpod
  riverpod:
    path: ../../packages/riverpod
