name: marvel
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: "> 1.17.0"

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod:
    path: ../../packages/hooks_riverpod
  flutter_hooks: ^0.11.0
  cupertino_icons: ^0.1.3
  freezed_annotation: ^0.11.0
  dio: ^3.0.9
  crypto: ^2.1.4
  flutter_svg: ^0.18.0
  flutter_portal: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^0.11.0
  mockito: ^4.1.0
  build_runner: ^1.9.0
  json_serializable: ^3.3.0

dependency_overrides:
  flutter_riverpod:
    path: ../../packages/flutter_riverpod
  riverpod:
    path: ../../packages/riverpod
  hooks_riverpod:
    path: ../../packages/hooks_riverpod

flutter:
  uses-material-design: true
  assets:
    - assets/configurations.json
    - assets/marvel.svg
    - assets/marvel_background.jpeg