name: marvel
description: A new Flutter project.
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  crypto: ^3.0.0
  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  flutter_portal: ^0.4.0
  flutter_svg: ^0.21.0+1
  freezed_annotation: ^2.1.0
  hooks_riverpod:
    path: ../../packages/hooks_riverpod
  json_annotation: ^4.6.0

dev_dependencies:
  build_runner: ^2.0.0
  custom_lint: ^0.6.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0
  json_serializable: ^6.3.1
  mockito: ^5.0.0
  riverpod_lint:
    path: ../../packages/riverpod_lint

dependency_overrides:
  flutter_riverpod:
    path: ../../packages/flutter_riverpod
  hooks_riverpod:
    path: ../../packages/hooks_riverpod
  riverpod:
    path: ../../packages/riverpod

flutter:
  uses-material-design: true
  assets:
    - assets/configurations.json
    - assets/marvel.svg
    - assets/marvel_background.jpeg
